import { PlanetsContainer } from '@/container/planets-container/planets-container';
import { Metadata } from 'next';
import { ParsedUrlQuery } from 'querystring';
import React from 'react';

interface PlanetsPageInterfaceProps {
  params: ParsedUrlQuery;
}

export const metadata: Metadata = {
  title: 'Information about the planets',
  description: 'Generated by create next app',
};

const PlanetsPage = ({ params }: PlanetsPageInterfaceProps) => {
  const planetName = params?.id ?? 'mercury';
  return (
    <div>
      <PlanetsContainer planetName={planetName as string} />
    </div>
  );
};

export default PlanetsPage;
